### ISSUE TITLE
BUG: login page styles

### ISSUE THREAD

**Issue by tatsmaki** [curriculum-vitae-team/cv-Ensign-Papkevich#8]
![Image](https://user-images.githubusercontent.com/61022192/217067083-70689f56-e75b-4843-ac13-c62d8a055fb7.png)

1) password input width
2) password is 12345 - but error says it should be at least 5 characters

![Image](https://user-images.githubusercontent.com/61022192/217067299-ba4e55b7-a29c-40e9-8b54-3f6ef7fa941b.png)

3) profile and logout are available for unauthorized user

**Comment by alensign** [comment]
![image](https://user-images.githubusercontent.com/99127721/219950600-fa6c2457-7c92-44ed-84de-155447c5f4d1.png)
login page is fixed: page style was unified with the Sign up page, password input field works correctly
